### ISSUE TITLE
Python module kerastuner was not found...

### ISSUE THREAD

**Issue by Steviey** [henry090/kerastuneR#29]
************************************************
Win7
R 4.x
***********************************************

Hello Folks,
thank you for this wonderful work. Some issues:

kerastuneR itself quits on 

`kerastuneR::install_kerastuner() `

with...

"Error: Installing Python packages into a virtualenv is not supported on Windows"

Successful installation of package "keras-tuner" with: 

```
use_condaenv("r-reticulate")
py_run_string("import gc
gc.collect()")
conda_install("r-reticulate",c('keras-tuner'), pip = TRUE)
```
results later for kerastuneR in:  

"Python module kerastuner was not found"

What to do?

**Comment by henry090** [comment]
Hi. Please, refer to the official documentation: https://rstudio.github.io/reticulate/articles/python_packages.html

**Comment by Steviey** [comment]
I already did so. Anyways- switched to Ubuntu.
